assetPrefix = "powerplant";

stage3Cost = 10000;

plantInfo = {
  "4": {"resource": "coal", "intake": 2, "output": 1},
  "8": {"resource": "coal", "intake": 3, "output": 2},
  "10": {"resource": "coal", "intake": 2, "output": 2},
  "15": {"resource": "coal", "intake": 2, "output": 3},
  "20": {"resource": "coal", "intake": 3, "output": 5},
  "25": {"resource": "coal", "intake": 2, "output": 5},
  "31": {"resource": "coal", "intake": 3, "output": 6},
  "36": {"resource": "coal", "intake": 3, "output": 7},
  "42": {"resource": "coal", "intake": 2, "output": 6},
  "3": {"resource": "oil", "intake": 2, "output": 1},
  "7": {"resource": "oil", "intake": 3, "output": 2},
  "9": {"resource": "oil", "intake": 1, "output": 1},
  "16": {"resource": "oil", "intake": 2, "output": 3},
  "26": {"resource": "oil", "intake": 2, "output": 5},
  "32": {"resource": "oil", "intake": 3, "output": 6},
  "35": {"resource": "oil", "intake": 1, "output": 5},
  "40": {"resource": "oil", "intake": 2, "output": 6},
  "5": {"resource": "hybrid", "intake": 2, "output": 1},
  "12": {"resource": "hybrid", "intake": 2, "output": 2},
  "21": {"resource": "hybrid", "intake": 2, "output": 4},
  "29": {"resource": "hybrid", "intake": 1, "output": 1},
  "46": {"resource": "hybrid", "intake": 3, "output": 7},
  "6": {"resource": "gas", "intake": 1, "output": 1},
  "14": {"resource": "gas", "intake": 2, "output": 2},
  "19": {"resource": "gas", "intake": 2, "output": 3},
  "24": {"resource": "gas", "intake": 2, "output": 4},
  "30": {"resource": "gas", "intake": 3, "output": 6},
  "38": {"resource": "gas", "intake": 3, "output": 7},
  "11": {"resource": "uranium", "intake": 1, "output": 2},
  "17": {"resource": "uranium", "intake": 1, "output": 2},
  "23": {"resource": "uranium", "intake": 1, "output": 3},
  "28": {"resource": "uranium", "intake": 1, "output": 4},
  "34": {"resource": "uranium", "intake": 1, "output": 5},
  "39": {"resource": "uranium", "intake": 1, "output": 6},
  "13": {"resource": "green", "intake": 0, "output": 1},
  "18": {"resource": "green", "intake": 0, "output": 2},
  "22": {"resource": "green", "intake": 0, "output": 2},
  "27": {"resource": "green", "intake": 0, "output": 3},
  "33": {"resource": "green", "intake": 0, "output": 4},
  "37": {"resource": "green", "intake": 0, "output": 4},
  "44": {"resource": "green", "intake": 0, "output": 5},
  "50": {"resource": "green", "intake": 0, "output": 6},
};
plantNames = [];
for (let cost in plantInfo) {
  plantNames.push("plant" + cost);
}
germanCities = [
  "FLENSBURG",
  "KIEL",
  "HAMBURG",
  "HANNOVER",
  "BREMEN",
  "CUXHAVEN",
  "WILHELMSHAVEN",
  "OSNABRUCK",
  "MUNSTER",
  "ESSEN",
  "DUISBURG",
  "DUSSELDORF",
  "DORTMUND",
  "KASSEL",
  "AACHEN",
  "KOLN",
  "TRIER",
  "WIESBADEN",
  "SAARBRUCKEN",
  "MANNHEIM",
  "FRANKFURT-M",
  "STUTTGART",
  "FREIBURG",
  "KONSTANZ",
  "AUGSBURG",
  "MUNCHEN",
  "REGENSBURG",
  "PASSAU",
  "NURNBERG",
  "WURZBURG",
  "FULDA",
  "ERFURT",
  "HALLE",
  "LEIPZIG",
  "DRESDEN",
  "MAGDEBURG",
  "BERLIN",
  "FRANKFURT-D",
  "SCHWERIN",
  "TORGELOW",
  "ROSTOCK",
  "LUBECK",
];

assetNames = ["Germany", "supply", "coal", "oil", "gas", "uranium", "stage3"].concat(germanCities).concat(plantNames);
serverNames = {};
