# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint autopep8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Auto-formatting with autopep8
      uses: wearerequired/lint-action@v2
      with:
        auto-fix: ${{ github.event_name == 'pull_request' }}
        commit_message: "Fix code style issues with ${linter}"
        autopep8: true
  lint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint autopep8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analyze the code with pylint
      run: |
        pylint -j 0 **/*.py
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint autopep8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Tests
      run: |
        python -m unittest
